config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :recurring_events
  root to:'pages#calendar'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/recurring_event.rb
class RecurringEvent < ApplicationRecord
	
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
 

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
   @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    if @event.destroy
      redirect_to root_path
    end

  end
  
  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def calendar
	    
	end

end

app/controllers/recurring_events_controller.rb
class RecurringEventsController < ApplicationController
  before_action :set_recurring_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @recurring_events = RecurringEvent.all  
  end

  # GET /events/1
  # GET /events/1.json
  def show
   
  end

  # GET /events/new
  def new
    @recurring_event = RecurringEvent.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @recurring_event = RecurringEvent.new(recurring_event_params)
    

    respond_to do |format|
      if @recurring_event.save
        format.html { redirect_to @recurring_event, notice: 'Recurring Event was successfully created.' }
        format.json { render :show, status: :created, location: @recurring_event }
      else
        format.html { render :new }
        format.json { render json: @recurring_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @recurring_event.update(event_params)
        format.html { redirect_to @recurring_event, notice: 'Recurring Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @recurring_event }
      else
        format.html { render :edit }
        format.json { render json: @recurring_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @recurring_event.destroy
    respond_to do |format|
      format.html { redirect_to recurring_events_url, notice: 'Recurring Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurring_event
      @recurring_event = RecurringEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurring_event_params
      params.require(:recurring_event).permit(:name, :start_time, :recurring)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Edit Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event, remote: true do |f| %>
<ul class="form-style-1">
  <div class="form-inputs">
    <li>
      <%= f.input :title, placeholder: 'Name of Event', label:false %>
    </li>
    <li>
      <%= f.input :date_range, placeholder: 'Date Range', label:false,  input_html: { class: "form-control input-sm date-range-picker" } %>
    </li>
    <%= f.input_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden' %>
    <%= f.input_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden' %>
    
    <li>
      <%= f.input :color, placeholder: 'Color', label:false, as: :select, collection: [['Bold Blue','#5484ed'], ['Blue','#a4bdfc'], ['Turquoise','#46d6db'],['Bold Green','#51b749'], ['Green','#7ae7bf'], ['Yellow','#fbd75b'],['Orange','#ffb878'], ['Pink','#ff887c'], ['Bold Red','#dc2127'], ['Purple','#dbadff'], ['Gray','#e1e1e1']]%>
    </li>
    
  </div>

  <div class="form-actions">
    <li>
      <%= f.button :submit %>
      
      <%= link_to 'Delete', 
                  event, 
                  method: :delete, 
                  class: 'btn btn-danger', 
                  data: { confirm: 'Are you sure?' }, 
                  remote: true unless @event.new_record? %>
    </li>
  </div>
<% end %>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id= new_event_title>Create New Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/create.js.erb
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.start %></td>
          <td><%= event.finish %></td>
          <td><%= event.color %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.finish %>
</p>

<p>
  <strong>Color:</strong>
  <%= @event.color %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"), 
  true
);
$('.modal').modal('hide');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventPlanner</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-root" content="/app">
  </head>

  <body>
    <%= yield %>
    <div id='remote_container'></div>
  </body>
</html>

app/views/pages/calendar.html.erb
<div class = "row">
	<div class = "col-md-offset-2 col-md-8">
		<div class='calendar'></div>
	</div>
</div>

app/views/recurring_events/_form.html.erb
<%= form_for @recurring_event do |f| %>
  <% if @recurring_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recurring_event.errors.count, "error") %> prohibited this recurring event from being saved:</h2>

      <ul>
      <% @recurring_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :select_for_options %>
    <%= f.select_recurring :recurring%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recurring_events/edit.html.erb
<h1>Editing Recurring Event</h1>

<%= render 'form', recurring_event: @recurring_event %>

<%= link_to 'Show', @recurring_event %> |
<%= link_to 'Back', recurring_events_path %>

app/views/recurring_events/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>Recurring</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recurring_events.each do |recurring_event| %>
      <tr>
        <td><%= recurring_event.name %></td>
        <td><%= recurring_event.start_time %></td>
        <td><%= recurring_event.recurring %></td>
        <td><%= link_to 'Show', recurring_event %></td>
        <td><%= link_to 'Edit', edit_recurring_event_path(recurring_event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %> |
<%= link_to 'New Recurring Event', new_recurring_event_path %>

app/views/recurring_events/new.html.erb
<h1>New Recurring Event</h1>

<%= render 'form', recurring_event: @recurrign_event %>

<%= link_to 'Back', recurring_events_path %>

app/views/recurring_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recurring_event.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @time %>
</p>

<p>
  <strong>Recurring:</strong>
  <%= @recurring_event.recurring %>
</p>




<%= link_to "Delete This Set of Recurring Events", recurring_event_path(@recurring_event), method: :delete %>

<%= link_to 'Edit', edit_recurring_event_path(@recurring_event) %> |
<%= link_to 'Back', recurring_events_path %>